version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: hr-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hr_system
      POSTGRES_USER: hradmin
      POSTGRES_PASSWORD: rahasia123
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - hr-network

  # Backend API (Node.js Express)
  backend:
    build: ./backend
    container_name: hr-backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: hradmin
      DB_PASSWORD: rahasia123
      DB_NAME: hr_system
      JWT_SECRET: supersecretkeygantidaripenting
      PORT: 5000
    ports:
      - "5000:5000"
    networks:
      - hr-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: hr-nginx
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - hr-network

networks:
  hr-network:
    driver: bridge
